name: Auto Assign & Review

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      # 1. Assignee를 PR 생성자(본인)로 자동 지정
      - name: Auto Assign
        uses: akasaito/auto-assign-action@v3
        with:
          configuration-path: ".github/auto-assign.yml"

      # 2. Reviewers를 팀원 전체로 자동 지정
      - name: Request Reviewers
        uses: rowi1sh/auto-request-review-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: "oxcm07,hjhn120,hj-66,bangyewon,Bin-925"